### ISSUE TITLE
Error when running a small example

### ISSUE THREAD

**Issue by gallak** [TrueSerenity/booked-php-api-client#2]
When I tried to execute a simple code I got the following error

```
root@vm1:/var/www/booked/apiweb# php5 test.php 
PHP Fatal error:  Cannot redeclare bookedAPIclient::buildResourceObject
```

my code : 

```
<?php
require_once('bookedapi.php');
//some of your code
session_start();
$username = "admin";
$password = "******";
$bookedapiclient = new bookedapiclient($username, $password);
print_r($bookedapiclient);
$bookedapiclient->authenticate(true);
//the next call will get all reservations for the current user or all of them if that user is the admin
$allReservations = $bookedapiclient->getReservation();
//print the result to the screen
print_r($allReservations);
?>
```

I see on your library too declaration of buildResourceObject function is it normal ?

I using php5.6.6 on debian Jessie

thanks

**Comment by TwinMist** [comment]
getting the same error
any fix?
PHP Fatal error:  Cannot redeclare bookedAPIclient::buildResourceObject()

**Comment by LifeSteala** [comment]
I have the same error. Is there a fix for this?

Fatal error: Cannot redeclare bookedAPIclient::buildResourceObject() in bookedapi.php on line 1127

**Comment by ryanccrawford** [comment]
I haven't updated this code in quite some time. I'm sure that Booked has changed a few times since. I will definitely take a look and see what I can do to bring it up to date. Just give me a few days and I'll post a new version. As far as the error is concerned, I wouldn't know until I tested it. There a good chance its nothing you're doing wrong.

Sent from my HTC

----- Reply message -----

**Comment by robp2175** [comment]
any chance you might update this to work with the current version. I appreciate your efforts.

**Comment by mytrueserenity** [comment]
I would love to. I love coding it's my passion. The problem is I'm expecting a new little one soon. I have had trouble finding time to breathe. Every time I turn around something else needs to be done. So being that coding is my hobby, I'll have to honestly answer your question with.. No. Not at this moment. I really hate saying that. But perhaps in the next few months when everything settles down a bit. I'm sure by then you'll have found another solution.

Thanks for your understanding

Sent from my HTC

----- Reply message -----
